### PR TITLE
Use API to get markdown content

### PR DESCRIPTION
**Pull request by jdabtieu**
PicoCTF, one of the largest CTF platforms loads content through an API instead of directly. This appears to be a good way to stop malformed HTML from polluting the rest of the page (therefore bypassing DOMPurify, leading to cross-site scripting.

Currently, our markdown content (e.g. problem description, hints, announcements) is directly injected into the page, which leads to vulnerabilities where one could create malformed HTML to escape from the sandbox, and otherwise overwrite the page using CSS.

Adding an API to get this potentially unsafe content and pass it directly into Showdown + DOMPurify should stop this vulnerability by not allowing the content to interact with the page at all until it is purified. This can be done by injecting the content into an isolated div first, and then appending it to the page.

Another benefit of this is that people who would like to use an API to interact with the site now have a supported way to do so, albeit currently very limited in functionality.

The performance hit of the extra API calls can be partially mitigated using `link rel="preload"`. No page (under regular circumstances) should trigger more than 10 API calls.

### CODE REVIEW

**Comment by jdabtieu** [comment]
Two candidates:

1. Shadow DOM - css inside can't affect css outside (good), css outside can affect css inside (necessary for dark mode), but malicious divs (e.g. fullscreen) can still be created (bad)
2. iframe - css inside can't affect css outside (good), in fact anything inside can't affect anything outside (good), css outside can't affect css inside (not good for dark mode)

There might be more options but for now this is what I've tried. Turning off HTML access completely is not an option.

To fix the issue with shadow DOM, messing with z-index might be possible (i.e. set z-index of everything except container to 2, z-index of the container to 1)

To fix the issue with iframe, it might be possible to rewrite the darkMode script to be able to also change iframe contents.

**Comment by jdabtieu** [comment]
TODO: Apply global styles to shadow DOM

**Comment by jdabtieu** [comment]
@slightlyskepticalpotat can you take a look at this, I know it's a lot but this is a quite big & important change

I'll also do a final review before pushing to master

**Review by slightlyskepticalpotat — APPROVED** [review]
utACK, but we should probably add a special warning in the migrate script before next version

please hold off on merging this until I test it tomorrow

**Comment by jdabtieu** [comment]
> utACK, but we should probably add a special warning in the migrate script before next version

Yes, I'm planning to do that since I'm probably also going to make some more breaking changes that will bump CTFOJ to v3.0.0.

Also I won't merge until a few days later, I'm also doing a review as well.

**Comment by slightlyskepticalpotat** [comment]
Tested and everything is working fine, but I discovered an unrelated issue https://github.com/jdabtieu/CTFOJ/issues/117.

**Pull request merged**
