### PR TITLE
edit flag

### PR DESCRIPTION
**Pull request by ComputerGenius152**
closes https://github.com/jdabtieu/CTFOJ/issues/62

### CODE REVIEW

**Comment by jdabtieu** [comment]
Editing the flag should not be required, but rather, optional. Please change that in application.py

I'll see why the tests failed, not sure how that could have happened

**Comment by ComputerGenius152** [comment]
Editing the flag is optional, but the original value of flag must still stay in the box or it'll be changed.

I figured out the situation with the tests was because the test edited a problem without the flag, and I ran them on a wrong version of the program.

**Comment by jdabtieu** [comment]
Wouldn't it be possible to run a check like
```
if not new_flag:
  run code
else:
  run other code
```

**Comment by ComputerGenius152** [comment]
I checked and this is how we do it with most of the other fields, so I
thought it was best to keep things consistent

**Comment by jdabtieu** [comment]
Hmm, ok.
My main concern is that we shouldn't leak the flag to admins, to avoid
spoiling problems, and also to avoid increasing the reward of a phising
attack

**Pull request merged**
